### ISSUE TITLE
Fix / remove warnings in Masonry documentation

### ISSUE THREAD

**Issue by waywardmonkeys** [linebender/xilem#449]
Separate from #389, the warnings when running `cargo doc -p masonry` need to be fixed.

Most of them are about things that no longer exist within masonry or have perhaps changed names, so it should be a pretty quick pass.

This is blocking re-enabling denying warnings within CI for xilem documentation and has already led to an issue in that regard with a broken link making its way into there.

**Comment by waywardmonkeys** [comment]
This is even worse with `cargo clippy -- -W clippy::doc_markdown` and that has even more regressions in `xilem_core`, `xilem_web`, and `xilem`.

**Comment by PoignardAzur** [comment]
This should be fixed by #815. Are there still errors?

**Comment by DJMcNab** [comment]
This issue also tracks re-enabling these issues in CI. Is that resolved?

**Comment by PoignardAzur** [comment]
Well I didn't chnage CI after fixing the doc errors, so probably not.

**Comment by DJMcNab** [comment]
It looks like https://github.com/linebender/xilem/pull/815/files#diff-27b19fb95b25f32e39ea044b6ab68ee4a84d37944078b20ea52985fcca779e7aL112-L115 should have addressed this, I think.

The only thing that's still wrong is https://github.com/linebender/xilem/blob/d77b31b892cfc5390c3fd49bc2f41da4101e3f24/masonry/src/app/tracing_backend.rs#L4

which is redundant I think. It looks like these were being suppressed by `allow`s rather than anything in the CI script.

**Comment by waywardmonkeys** [comment]
@DJMcNab I'd removed that locally yesterday but didn't get to submitting the PR. Done now as #855.
